# Generated by Django 5.0.6 on 2024-07-14 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boaapp", "0002_audiofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uploaded_file", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
