# Generated by Django 5.0.6 on 2024-07-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boaapp", "0003_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="document",
            name="uploaded_file",
            field=models.FileField(upload_to=""),
        ),
    ]
