# Generated by Django 5.0.6 on 2024-07-15 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boaapp", "0004_alter_document_uploaded_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiofile",
            name="metadata",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="audiofile",
            name="title",
            field=models.CharField(default="Untitled", max_length=100),
        ),
    ]
