# Generated by Django 5.1 on 2024-10-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boaapp', '0005_audiofile_metadata_audiofile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioVideo',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(blank=True, max_length=255)),
                ('video_file', models.FileField(upload_to='portfolio/videos/')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeDocument',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='resume/')),
            ],
        ),
        migrations.CreateModel(
            name='ScrollingImage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('image', models.ImageField(upload_to='scrolling_images/')),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(upload_to='', verbose_name='Upload A File'),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('project_url', models.URLField(blank=True, null=True)),
                (
                    'companylogo',
                    models.ImageField(blank=True, null=True, upload_to='portfolio/'),
                ),
                (
                    'image',
                    models.ImageField(blank=True, null=True, upload_to='portfolio/'),
                ),
                (
                    'ppt_file',
                    models.FileField(blank=True, null=True, upload_to='portfolio_ppts/'),
                ),
                (
                    'videos',
                    models.ManyToManyField(
                        blank=True,
                        related_name='portfolio_items',
                        to='boaapp.portfoliovideo',
                    ),
                ),
                (
                    'scrolling_images',
                    models.ManyToManyField(blank=True, to='boaapp.scrollingimage'),
                ),
            ],
        ),
        migrations.CreateModel(
            name='DevopsItem',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                (
                    'logo',
                    models.ImageField(blank=True, null=True, upload_to='portfolio/'),
                ),
                (
                    'img',
                    models.ImageField(blank=True, null=True, upload_to='portfolio/'),
                ),
                (
                    'vid',
                    models.FileField(blank=True, null=True, upload_to='portfolio/videos/'),
                ),
                (
                    'ppt',
                    models.FileField(blank=True, null=True, upload_to='portfolio_ppts/'),
                ),
                (
                    'scrolling_images',
                    models.ManyToManyField(blank=True, to='boaapp.scrollingimage'),
                ),
            ],
        ),
    ]
