# Generated by Django 5.1 on 2025-05-10 15:30

import boaapp.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("boaapp", "0008_alter_audiofile_document_alter_audiofile_metadata_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrollment",
            name="create_step_completed",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="learn_step_completed",
        ),
        migrations.RemoveField(
            model_name="enrollment",
            name="teach_step_completed",
        ),
        migrations.CreateModel(
            name="CourseSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Order in which the section appears in the course.",
                    ),
                ),
                (
                    "learn_content_file",
                    models.FileField(
                        blank=True,
                        help_text="e.g., .ipynb, .md, .pdf for the 'Learn' step.",
                        null=True,
                        upload_to=boaapp.models.course_section_learn_path,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Brief overview of this section."
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="boaapp.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.AddField(
            model_name="enrollment",
            name="completed_learn_sections",
            field=models.ManyToManyField(
                blank=True,
                related_name="completed_by_enrollments",
                to="boaapp.coursesection",
            ),
        ),
    ]
