# Generated by Django 5.1.15 on 2026-04-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boaapp', '0011_chatconversation_chatmessage_codereview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='question_type',
            field=models.CharField(
                choices=[('mcq', 'Multiple Choice'), ('code', 'Code Challenge'), ('short', 'Short Answer')],
                default='mcq',
                max_length=20,
            ),
        ),
    ]
