# Generated by Django 5.1.15 on 2026-04-12 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('boaapp', '0012_quiz_question_type_maxlength'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='audio_data',
            field=models.BinaryField(
                blank=True, help_text='MP3 bytes stored in PostgreSQL for persistence across deploys.', null=True
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='notebook_json',
            field=models.TextField(
                blank=True,
                default='',
                help_text='Raw .ipynb JSON stored in the database so it survives ephemeral deploys.',
            ),
        ),
        migrations.AddField(
            model_name='document',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='file',
            field=models.FileField(blank=True, upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
